### ISSUE TITLE
metric的label包含实例名称

### ISSUE THREAD

**Issue by jackiehope** [nevill/cloudmonitor_exporter#1]
目前取到的metric都是只包含实例ID不方便查看，是否可以支持实例name等信息

**Comment by nevill** [comment]
目前没打算支持这个特性。要将 name 与 ID 关联需要调用另外的 API 查询，这样子会增加这个项目的复杂度，而且需要考虑缓存这些信息。更好的办法是做一个 Grafana 插件来完成这个对应的事情，cloudmonitor_exporter 仅用来提供数据。

**Comment by jackiehope** [comment]
@nevill 嗯，这几天尝试通过describe接口结合datapoint在metric里面添加name，虽然麻烦点，至少可用。刚搜了一下Grafana插件，没找到有实现功能的，不知道有没有类似功能插件的推荐一下。

**Comment by nevill** [comment]
据我所知，并没有类似插件，有兴趣的话可以自己撸一个。
